name: "Main Pipeline"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  version:
    name: Validate Version
    uses: ./.github/workflows/callable.version.yml

  build:
    needs: version
    name: Build + unit tests
    uses: ./.github/workflows/callable.build.yml

  tag:
    needs: build
    name: Tag Version
    uses: ./.github/workflows/callable.set-tag.yml
    if: (github.ref == 'refs/heads/master')

  publish_github_pkg:
    needs: tag
    secrets: inherit
    name: Publish artifact (Github Packages)
    uses: ./.github/workflows/callable.publish-gh-package.yml
    if: (github.ref == 'refs/heads/master')

  release:
    needs: tag
    name: Release
    uses: ./.github/workflows/callable.release.yml

  publish_javadoc:
    needs: build
    name: Publish javadoc (GitHub Pages)
    permissions:
      contents: write
    uses: ./.github/workflows/callable.publish-javadoc.yml
    if: (github.ref == 'refs/heads/master')

#  publish_sonatype:
#    name: Publish artifact (Maven Central)
#    uses: ./.github/workflows/callable.publish-sonatype.yml
#    needs: build
#    secrets: inherit
#    if: |
#      (
#        github.event_name != 'workflow_dispatch'
#        || inputs.type == '...no release'
#      ) && (
#        github.ref == 'refs/heads/master'
#        || github.ref_type == 'tag'
#      )