name: "Main Pipeline"

on:
  push:
    branches:
      - master

jobs:
  version:
    name: Version Project
    uses: ./.github/workflows/callable.version.yml

  build:
    needs: version
    name: Build + unit tests
    uses: ./.github/workflows/callable.build.yml

  tag:
    needs: build
    name: Tag Version
    uses: ./.github/workflows/callable.set-tag.yml
    if: (github.ref == 'refs/heads/master')

#  publish_sonatype:
#    name: Publish artifact (Maven Central)
#    uses: ./.github/workflows/callable.publish-sonatype.yml
#    needs: build
#    secrets: inherit
#    if: |
#      (
#        github.event_name != 'workflow_dispatch'
#        || inputs.type == '...no release'
#      ) && (
#        github.ref == 'refs/heads/master'
#        || github.ref_type == 'tag'
#      )