name: "Main Pipeline"

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build + unit tests
    uses: ./.github/workflows/callable.build.yml

  publish_sonatype:
    name: Publish artifact (Maven Central)
    uses: ./.github/workflows/callable.publish-sonatype.yml
    needs: build
    if: |
      (
        github.event_name != 'workflow_dispatch'
        || inputs.type == '...no release'
      ) && ( 
        github.ref == 'refs/heads/master' 
        || github.ref_type == 'tag' 
      )

#  publish_sonatype:
#    name: Publish artifact (Maven Central)
#    runs-on: ubuntu-latest
#    needs: build
#    if: |
#      (
#        github.event_name != 'workflow_dispatch'
#        || inputs.type == '...no release'
#      ) && (
#        github.ref == 'refs/heads/master'
#        || github.ref_type == 'tag'
#      )
#    steps:
#      - name: Checkout project sources
#        uses: actions/checkout@v4
#
#      - name: Set up Java
#        uses: actions/setup-java@v4
#        with:
#          java-version: '8.0.412+8'
#          distribution: 'temurin'
#          server-id: ossrh
#          server-username: IoHm+1df
#          server-password: 0C/92WOT1qdbqKh8xIuLWidatHeYiBNGyiIcEwExmZ92
#          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
#          gpg-passphrase: Uneven1-Mashed-Matchbook
#
#      - name: Copy xml to .m2 directory
#        run: |
#          cp .github/maven/settings.xml /home/runner/.m2/
#
#      - name: Set Version Artefact
#        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}
#
#      - name: Deploy in Sonatype
#        run: mvn clean -P release deploy -DskipTests
#        env:
#          MAVEN_USERNAME: IoHm+1df
#          MAVEN_CENTRAL_TOKEN: 0C/92WOT1qdbqKh8xIuLWidatHeYiBNGyiIcEwExmZ92
#          MAVEN_GPG_PASSPHRASE: Uneven1-Mashed-Matchbook
#          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}