name: Version Validate

on:
  workflow_call:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8.0.412+8'
          distribution: 'temurin'
          cache: maven

      - name: Validate Maven version
        id: validate
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          EXPECTED_VERSION_REGEX="^1\.[0-9]+\.[0-9]+(-SNAPSHOT)?$"
          
          if [[ "$VERSION" =~ $EXPECTED_VERSION_REGEX ]]; then
            echo "### :notice: Build completed successfully! :rocket:" >> $GITHUB_STEP_SUMMARY
            echo "Version $VERSION is valid."
          else
            echo "Version $VERSION is invalid. Expected pattern: $EXPECTED_VERSION_REGEX"
            exit 1
          fi