name: Publish to Sonatype
on:
  workflow_call:

jobs:
  publish:
    name: Maven publish (Maven Central)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '8.0.412+8'
          distribution: 'temurin'
          server-id: ossrh
          server-username: IoHm+1df
          server-password: 0C/92WOT1qdbqKh8xIuLWidatHeYiBNGyiIcEwExmZ92
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: Uneven1-Mashed-Matchbook

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_SIGNING_KEY }}" | gpg --batch --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Copy xml to .m2 directory
        run: |
          cp .github/maven/settings.xml /home/runner/.m2/

      - name: Set Version Artefact
        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}

      - name: Deploy in Sonatype
        run: mvn clean -P release deploy -DskipTests
        env:
          MAVEN_USERNAME: IoHm+1df
          MAVEN_CENTRAL_TOKEN: 0C/92WOT1qdbqKh8xIuLWidatHeYiBNGyiIcEwExmZ92
          MAVEN_GPG_PASSPHRASE: Uneven1-Mashed-Matchbook
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}