name: Create Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Changelog goes here...
