name: Create Release
on:
  workflow_call:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
