name: Publish package to the Maven Central Repository

on:
  workflow_call:

jobs:
  publish:
    name: Publish in Sonatype
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '8.0.412+8'
          distribution: 'temurin'
          server-id: ossrh
          server-username: IoHm+1df
          server-password: 0C/92WOT1qdbqKh8xIuLWidatHeYiBNGyiIcEwExmZ92
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: Uneven1-Mashed-Matchbook

      - name: Import GPG key
        run: |
          gpg --batch --import ./.github/key/0x685C7CA7-pub.asc
          gpg --batch --import ./.github/key/0x685C7CA7-sec.asc

      - name: Set Version Artefact
        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}

      - name: Deploy in Sonatype
        run: mvn clean -P release deploy -DskipTests
        env:
          MAVEN_GPG_PASSPHRASE: Uneven1-Mashed-Matchbook